micronaut:
  application:
    name: minesweeper
  server:
    port: 18888
    cors:
      enabled: true
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    entity-scan:
      packages:
        - 'com.deviget.persistence'
    properties:
      hibernate:
        hbm2ddl:
          auto: create