micronaut:
  application:
    name: minesweeper
  server:
    port: 18888
    cors:
      enabled: true
  datasources:
    default:
      url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
      username: ${JDBC_USER:sa}
      password: ${JDBC_PASSWORD:""}
      driverClassName: ${JDBC_DRIVER:org.h2.Driver}
  jpa:
    default:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          show_sql: true
          bytecode:
          provider: none